# Generated by Django 4.1 on 2022-08-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjProfHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjectives_list', models.JSONField(null=True)),
                ('profession_list', models.JSONField(null=True)),
                ('adjective_profession', models.JSONField(null=True)),
                ('places_list', models.JSONField(null=True)),
            ],
        ),
    ]
