# Generated by Django 4.1 on 2022-08-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limerines', '0002_templatehelper'),
    ]

    operations = [
        migrations.CreateModel(
            name='RhymePronHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhymes', models.JSONField(null=True)),
                ('pronounciation', models.JSONField(null=True)),
            ],
        ),
    ]
