# Generated by Django 4.1 on 2022-08-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limerines', '0004_rename_pronounciation_rhymepronhelper_pronunciation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limerick',
            old_name='pronounciation',
            new_name='pronunciation',
        ),
    ]
