# Generated by Django 4.1 on 2022-08-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limerines', '0006_embeddingshelper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmbeddingsHelper',
        ),
    ]
