# Generated by Django 4.1 on 2022-08-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limerines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_verse_templates', models.JSONField(null=True)),
                ('third_verse_templates', models.JSONField(null=True)),
                ('fourth_verse_templates', models.JSONField(null=True)),
                ('fifth_verse_templates', models.JSONField(null=True)),
            ],
        ),
    ]
